CREATE TABLE IF NOT EXISTS questions (id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, question varchar(256) not null, answer varchar(256) not null);
CREATE TABLE IF NOT EXISTS case_effects (id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, description varchar(256) not null, dtype varchar(31) not null);
CREATE TABLE IF NOT EXISTS cases (id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, position integer not null, effect_id integer references case_effects(id));
CREATE TABLE IF NOT EXISTS boards (id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, size integer not null);
CREATE TABLE IF NOT EXISTS question_decks (id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY);
CREATE TABLE IF NOT EXISTS question_deck_questions (deck_id integer references question_decks(id), question_id integer references questions(id), primary key (deck_id, question_id));
CREATE TABLE IF NOT EXISTS pawns (id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, name varchar(256) not null, color integer not null, position integer not null, score integer not null);
CREATE TABLE IF NOT EXISTS game_sessions (id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, nb_faces integer not null, board_id integer references boards(id), deck_id integer references question_decks(id));
CREATE TABLE IF NOT EXISTS game_session_players (game_session_id integer references game_sessions(id), player_id integer references pawns(id), primary key (game_session_id, player_id));